Category.create(name: "Escola")
Category.create(name: "Consultório")
Category.create(name: "Lazer/Hobbies")
Category.create(name: "Contas Básicas")
Category.create(name: "Mercado")
Category.create(name: "Funcionário")
Category.create(name: "Material")
Category.create(name: "Alimentação")
Category.create(name: "Cuidados pessoais")
Category.create(name: "Fornecedor")
Category.create(name: "Casa")
Category.create(name: "Outros")